In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("customer_churn_data.csv")

In [3]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,C00001,Female,0,No,No,15,Yes,No,No,No,...,No,No,No,No,Two year,No,Mailed check,34.64,519.60,No
1,C00002,Male,0,No,No,24,Yes,No,DSL,No,...,No,Yes,Yes,No,One year,No,Bank transfer (automatic),95.56,2293.44,Yes
2,C00003,Male,0,Yes,Yes,30,Yes,No,No,No,...,No,No,No,No,One year,Yes,Bank transfer (automatic),24.25,727.50,Yes
3,C00004,Male,0,Yes,No,58,Yes,No,No,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,30.50,1769.00,No
4,C00005,Female,0,No,Yes,59,Yes,No,Fiber optic,Yes,...,No,No,Yes,Yes,Two year,Yes,Credit card (automatic),77.99,4601.41,Yes

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        1000 non-null   object
 1   gender            1000 non-null   object
 2   SeniorCitizen     1000 non-null   int64
 3   Partner           1000 non-null   object
 4   Dependents        1000 non-null   object
 5   tenure            1000 non-null   int64
 6   PhoneService      1000 non-null   object
 7   MultipleLines     1000 non-null   object
 8   InternetService   1000 non-null   object
 9   OnlineSecurity    1000 non-null   object
 10  OnlineBackup      1000 non-null   object
 11  DeviceProtection  1000 non-null   object
 12  TechSupport       1000 non-null   object
 13  StreamingTV       1000 non-null   object
 14  StreamingMovies   1000 non-null   object
 15  Contract          1000 non-null   object
 16  PaperlessBilling  1000 non-null   object
 17  PaymentMethod     1000 non-null   object
 18  MonthlyCharges    1000 non-null   float64
 19  TotalCharges      1000 non-null   float64
 20  Churn             1000 non-null   object
dtypes: float64(2), int64(2), object(17)
memory usage: 164.2+ KB

In [5]:
df.describe()

       SeniorCitizen       tenure  MonthlyCharges  TotalCharges
count    1000.000000  1000.000000     1000.000000   1000.000000
mean        0.151000    35.725000       68.280170   2420.887060
std         0.358228    20.989138       31.467141   1884.226148
min         0.000000     1.000000       20.050000     22.440000
25%         0.000000    17.000000       35.620000    926.722500
50%         0.000000    35.000000       70.500000   1868.975000
75%         0.000000    54.000000       95.612500   3716.962500
max         1.000000    72.000000      119.980000   8278.620000

In [6]:
df.isna().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

In [10]:
df["Churn"].value_counts()

Churn
No     772
Yes    228
Name: count, dtype: int64